
/**
  Generated by compiler
  - to generate run 'yarn dev:types'
*/
type Section = "Awesome Palestine" | "Table of Contents" | "Official" | "Documents &amp; Reports" | "Books" | "History" | "Politics" | "Israel" | "Zionism" | "Non-Jewish Zionism" | "Gaza" | "Arabs of Israel (48-Palestinians)" | "Archives" | "Movies" | "Media" | "War Supporting Companies" | "Open-Source Intelligence" | "Activists &amp; Journalists" | "Donations" | "Petitions" | "Pro-Palestine Websites"

type ConfigType = {
  excludeSections: Array<Section>
}

export default ConfigType;
